config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get "/tasks", to: "tasks#index"
  get "/tasks/new", to: "tasks#new"
  get "/tasks/details", to: "tasks#details"
  post "/tasks", to: "tasks#create"
  get "tasks/:id", to: "tasks#show", as: :task
  get "/tasks/:id/edit", to: "tasks#edit", as: :edit
  patch "tasks/:id", to: "tasks#update"
  patch "/tasks/:id/mark_completed", to: "tasks#mark_completed", as: "mark_completed_task"
  delete 'tasks/:id', to: 'tasks#destroy', as: 'delete_task'
  get '/tasks', to: 'tasks#index', as: 'back_to_tasks'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show_details
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path(@task)
  end

  def show
    @task = Task.find(params[:id])
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def mark_completed
    @task = Task.find(params[:id])
    @task.update(completed: true)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path, notice: 'Task was successfully destroyed.'
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/details.html.erb
<h1>Task name</h1>

app/views/tasks/edit.html.erb
<h1> Edit task </h1>

<%= form_with model: @task do |t| %>
  <%= t.label :title %>
  <%= t.text_field :title %>
  <%= t.label :details %>
  <%= t.text_field :details %>
  <%= t.label :completed %>
  <%= t.check_box :completed %>
  <%= t.submit %>
<% end %>

 <%= link_to "Back to Tasks", back_to_tasks_path %>

app/views/tasks/index.html.erb
<h1>List of tasks</h1>

<ol>
  <% @tasks.each do |task| %>
    <li>
      <%= link_to task_path(task.id) do %>
        <%= task.title %>
        <%= task.details %>
        <% if task.completed %>
          <i class="fa-regular fa-square-check"></i>
        <% else %>
          <i class="fa-regular fa-square"></i>
        <% end %>
      <% end %>
    </li>
    <% end %>
</ol>

app/views/tasks/new.html.erb
<h1> New task </h1>

<%= form_with model: @task do |t| %>
  <%= t.label :title %>
  <%= t.text_field :title %>
  <%= t.label :details %>
  <%= t.text_field :details %>
  <%= t.label :completed %>
  <%= t.check_box :completed %>
  <%= t.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<%= link_to 'Edit Task', edit_path(@task) %>

<p><%= @task.details %></p>

<p>
<%= @task.completed %>

<%= button_to 'Mark as completed', mark_completed_task_path(@task), method: :patch %>

 <%= button_to 'Delete Task', delete_task_path(@task), method: :delete, data: {  turbo_confirm: 'Are you sure you want to delete this task?' } %>
</p>

 <%= link_to "Back to Tasks", back_to_tasks_path %>